regen snakeoil ssl certs on docker build
muccg/docker-postgres-ssl pull request #3
Opened 2016-09-28 09:01 UTC by yveshwang

the cert's common name is a problem since the hostname is randomly created on the container. so regen snakeoil certs each time on build will work. you probably also want to extract at least the cert for the postgres client. 

pull request includes pg_hba.conf to use ssl, with trusted cred since the password is not set for postgres user. tightened up the postgressql.conf by specifying the snakeoil cert and key.

2016-09-29 02:17 UTC, aahunter commented
@grahame can you take a look at this please when you can.

2016-09-29 08:29 UTC, grahame requested changes
Thanks @yveshwang for the PR. Here is feedback which will need to be addressed for us to merge. Cheers!

2016-09-29 08:29 UTC, grahame commented on docker-entrypoint-initdb.d/pg_hba.conf
> +# PostgreSQL Client Authentication Configuration File
this file shouldn't be in the `docker-entrypoint-initdb.d/` directory - `docker-entrypoint.sh` will try to run it, which obviously won't work. I think it'd be a lot better to add a shell script which changes this as required, rather than reproducing the entire file in this project -- that way we'll get any helpful upstream changes and it'll be clearer what our changes are trying to do.

2016-09-29 08:29 UTC, grahame commented on docker-entrypoint-initdb.d/devssl.sh
>  cp /etc/ssl/certs/ssl-cert-snakeoil.pem $PGDATA/server.crt
is `hostname -f` necessary?

2016-09-29 08:29 UTC, grahame commented on docker-compose.yml
> +      - ./:/tmpmount
`tmpmount` doesn't look required for this to work - is this for debugging? if so, please remove from the PR

2016-12-12 10:24 UTC, closed without merging

2016-12-15 18:49 UTC, yveshwang commented on docker-entrypoint-initdb.d/pg_hba.conf
> +# PostgreSQL Client Authentication Configuration File
no it wouldn't. see `... it will run any *.sql files and source any *.sh scripts found in that directory to do further initialization before starting the service.` on https://hub.docker.com/_/postgres/

2016-12-15 18:50 UTC, yveshwang commented on docker-entrypoint-initdb.d/devssl.sh
>  cp /etc/ssl/certs/ssl-cert-snakeoil.pem $PGDATA/server.crt
`hostname -f` is for debugging.

2016-12-15 18:50 UTC, yveshwang commented on docker-compose.yml
> +      - ./:/tmpmount
purpose is to copy out of regenerated key and pem file if required. see export.sh.

2016-12-15 18:50 UTC, yveshwang commented
ah shame that didnt get merged. good luck anyways.